### ISSUE TITLE
Organize nupic.vision project

### ISSUE THREAD

**Issue by scottpurdy** [numenta/nupic.vision#19]
Proposed organization:

1. top level setup.py that installs as a namespace package importable as follows: `from nupic.vision import ...` -- we can then update numenta/nupic to specify nupic.vision as an "extra" that can optionally be included with the nupic install.
2. Either top level `src` directory or `nupic/vision` to contain the Python code. This is up for debate. The former is simpler but the latter is what we have done elsewhere.
3. `tests` directory should be part of the Python code, not a separate top-level directory (see numenta/nupic#2118). Examples and data should also be inside the Python package

**Comment by scottpurdy** [comment]
@oxtopus any comments on this?

**Comment by oxtopus** [comment]
My only input is to explicitly reinforce what is only subtly implied here: The name `nupic.vision` implies that the project will share a common import path with `nupic`, although the code is managed separately.  In practice, this is accomplished as namespace packages.

**Comment by scottpurdy** [comment]
@oxtopus - preference on `src/` vs. `nupic/vision/`? If no one has an opinion I will probably stick with the latter, which we have used elsewhere.

**Comment by jaredweiss** [comment]
I like the latter since it's consistent with what's used throughout the existing code
