### ISSUE TITLE
Update imports after move from NuPIC

### ISSUE THREAD

**Issue by breznak** [numenta/nupic.vision#5]
after #3 , this project depends on nupic `pip install nupic`; import paths need to be fixed. 

Can I have duplicit pathnames? Like from `nupic.regions.PyRegion import PyRegion` from "nupic package", and `from nupic.regions.ImageSensor import ImageSensor` from "local" ?

**Comment by breznak** [comment]
CC @rhyolight

**Comment by scottpurdy** [comment]
Obsolete now that ImageSensor has been moved. And there is still #19 for proper installation
