### ISSUE TITLE
No matching distribution found for nupic.vision

### ISSUE THREAD

**Issue by aqibmumtaz** [numenta/nupic.vision#60]
Hi Team,

On Installing nupic.vision I m getting following error:

```
Collecting nupic.vision
  Could not find a version that satisfies the requirement nupic.vision (from versions: )
No matching distribution found for nupic.vision

```

Please suggest how can I fix it.

**Comment by rhyolight** [comment]
How are you installing? I do not think this is on pypi. You'll need to install from source with `python setup.py install` right @scottpurdy ?

**Comment by scottpurdy** [comment]
You can use the command that @rhyolight listed or `pip install .` from the cloned repository directory.

**Comment by aqibmumtaz** [comment]
Thanks for your support @rhyolight @scottpurdy its getting installed now.
